### ISSUE TITLE
Request: More translatable items

### ISSUE THREAD

**Issue by XXY233** [Flowsqy/ShopChest#16]
The current ShopChest cannot translate items from versions 1.19 and 1.20.
![image](https://github.com/Flowsqy/ShopChest/assets/46647646/d90c4206-587a-40cb-bed2-045b6497eb39)

**Comment by XXY233** [comment]
Modified script: https://paste.gg/p/XXY233/fb4a1ac446924ca7b3d9016bee34d780
I modified the script a bit and it works, but I noticed one thing: if there are no new versions of the items in "entries.txt", then the script will not add and translate those items. I don't know how to add new versions of items to "entries.txt".

**Comment by Flowsqy** [comment]
I will work on this in a couple of hours

**Comment by Flowsqy** [comment]
After some investigations, it looks like there is no "short" solution. Each items are basically specified in the code and as the plugin is not truly maintained since 1.13, it should miss a lot of translation. The whole language system should be rewritten and it will takes time. So I will just do a partial fix here: 
- Split plugins messages and item translations in two different files. (To avoid touching to plugin messages when adding new item translations) (I should be able to do it in the upcoming hours)
- Create a new script to generate the new language file. (Probably tomorrow)

**Comment by Flowsqy** [comment]
Fixed. Some placeholders may be unavailable right now due to the new changes. Don't forget to read the `Instructions` section on the README. You can fin the new jar in the release section. I let you test it in details and close the issue if it works or comment if it doesn't.

**Comment by XXY233** [comment]
Thank you for your work! I tested it on a new server and the translation of the new items works fine.
![image](https://github.com/Flowsqy/ShopChest/assets/46647646/66d4b091-7465-4495-841a-418dfe276b82)

But there isn't any plugin language field in `messages-<locale>.lang` that can be translated, it's 0kb, which can be confusing for first-time users of the plugin.
![image](https://github.com/Flowsqy/ShopChest/assets/46647646/a93959a6-70cf-4518-8a67-c946bf7e048b)

**Comment by Flowsqy** [comment]
Well, it should have copied the en-US translations, x) I will check that

**Comment by Flowsqy** [comment]
Created a new issue for clarirty
