### ISSUE TITLE
ShopChest Big Memory leak

### ISSUE THREAD

**Issue by telfrancesco** [Flowsqy/ShopChest#19]
Hello! I have a purpur server with 250-300 players, my server crash often for java heap space, after 2-3 times, i created a dump and the memoryleak is shopchest. i will send the proofs of the dump open with Eclipse Memory Analyzer
![photo_2023-08-16_11-02-35](https://github.com/Flowsqy/ShopChest/assets/22562779/5cfd1eee-6fe0-4b86-ae3a-b1e4c9cd97b3)
![photo_2023-08-16_11-02-40](https://github.com/Flowsqy/ShopChest/assets/22562779/244e831c-8066-4c3c-ae8a-1f78ad7d1563)
![photo_2023-08-16_11-02-46](https://github.com/Flowsqy/ShopChest/assets/22562779/2d1503d5-0217-4290-b688-70f380d83ed5)
is possible to fix this memory leak and replace the method to update the shops, if possible remove the playermoveevent, i have 250-300 player that always move and performance-wise it's not the best 
![photo_2023-08-09_11-29-25](https://github.com/Flowsqy/ShopChest/assets/22562779/5dc75b7a-296c-44aa-846a-5df864abe969)

**Comment by Flowsqy** [comment]
I never touched this part of the plugin so rn I have no idea what's happening right there. Looking at your screens, it looks like some of the runnable are not cancelled. I will try to invistigate that but I can't say if I will have the time to fix it.

**Comment by Flowsqy** [comment]
After few investigations: 
- shops are loaded when chunks are loaded but seems to remain in memory (at least I found nothing to unload them.
- shop updater should be fast

My guess is that (considering your amount of player), the server reach at some point a too large amount of loaded shops. So it makes it longer for the updater to retrieve the shop to display and stacks in the queue waiting for processing. 

For now, the plugin take a queue of actions and process it one after another. It could be smarter to just process every moved player as it will limit memory consumption from 53 million objects (lmao wtf is that) to 200 or 300 (the amount of player).

Of course, even if it's apparently not the problem here (at least not the direct one), unloading shops located in unloaded chunks looks like a decent idea. 

That said, I'm curious to know what the memory analyzer tells about ShopUtils

**Comment by ytnoos** [comment]
53 milion objects because they accumulate indefinitely considering the fact that there are more actions being queued than the thread can extract and execute. Removing unloaded chunk shops from memory is quite useless, it means that the problem can recur whenever a considerable number of shops are present.

Maybe not forcing the update to every move but maybe updating it for all players every second would be a bit lighter on the server. Is it really necessary to make a call every time a player moves?

**Comment by Flowsqy** [comment]
I agree with you about the unloading. But as I said, it can still improve performances. 

Then, I think that we need to listen to player movement even if it directly transfer the information to another working thread. Although it would be "more logical" to create a separate thread that compute every player position every second, it would break user experience and force unnecessary calculation. It will cause some lag for what hologram the player is viewing (not updated as often as it should be) and make useless calculation (if the player is not moving).

Which brings to what I said. By queueing players instead of actions, we could retrieve last recorded position (with a wonderful concurrent hash map) and so always compute the last effective position of moving players. That system also allow to "clear" the queue easily as if it goes over a fixed limit, we could just clear the queue and add all existing position of every player to avoid desynchronization.

**Comment by Flowsqy** [comment]
I tried a (very) quick fix. Basically, it will now just clear the queue when it reaches 10 000 elements. Probably not perfect but as it only handle client side holograms, it should be safe. You can find the jar in the [release section](https://github.com/Flowsqy/ShopChest/releases/tag/v1.14.0-SNAPSHOT-MemoryLeakFix) as usual.

**Comment by Flowsqy** [comment]
I keep what I said for the rewrite, let me know if you see any unusual behavior on the long run.

**Comment by telfrancesco** [comment]
Sorry for the late reply, in these days the server isn't crash for memoryleak i presume the bug is fixxed
